spring:
   application:
      name: api-gateway
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
         routes:
            - id: product-microservice
              uri: lb://product-microservice
              predicates:
              - Path=/prod/**,/admin/**
            - id: user-microservice
              uri: lb://user-microservice
              predicates:
              - Path=/user/**
            - id: order-microservice
              uri: lb://order-microservice
              predicates:
              - Path=/ord/**
        
server:
   port: 8080

eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceURL:
         defaultZone: http://localhost:8761/eureka

management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway